---
# tasks file for ansible-role-awscli

- name: Install PIP
  apt: name="{{ 'python-pip' if ansible_distribution_version in ['14.04', '18.04'] else 'python3-pip' }}"

- name: Install AWS CLI from PIP
  pip: name="awscli"

# vim: set ft=ansible:set noet:ts=2:ws=2:
