---
name: Molecule
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '30 1 * * 3'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      container_supported: ${{ steps.get_min_ansible_container_version.outputs.result }}
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Pull Lint image
        run: docker pull -q ghcr.io/rheinwerk/molecule:lint

      - name: Ansible Linting
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/git -w /git ghcr.io/rheinwerk/molecule:lint ansible-lint --force-color -p --offline /git

      - name: Yaml Linting
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/git -w /git ghcr.io/rheinwerk/molecule:lint yamllint -f colored /git

      - name: Get min_ansible_container_version from meta/main.yml
        id: get_min_ansible_container_version
        uses: mikefarah/yq@master
        with:
          cmd: yq ".galaxy_info.min_ansible_container_version" ${GITHUB_WORKSPACE}/meta/main.yml

  molecule:
    name: Molecule for Ansible ${{ matrix.ansible_version }} / ${{ matrix.distro }} / Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    needs: lint
    if: needs.lint.outputs.container_supported != 'X'
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-20.04
            test_type: unit
            ansible_version: '>=2.9, <2.10'
            jinja2_version: '<3.1'
            python_version: '3.8'
            experimental: false
          - distro: ubuntu-20.04
            test_type: unit
            ansible_version: '>=2.10, <2.11'
            jinja2_version: '<3.1'
            python_version: '3.8'
            experimental: false
          - distro: ubuntu-20.04
            test_type: unit
            python_version: '3.8'
            jinja2_version: '<3.1'
            experimental: true
          - distro: ubuntu-22.04
            test_type: unit
            python_version: '3.10'
            experimental: true

    steps:
      - uses: Rheinwerk/molecule@v1
        with:
          distro: ${{ matrix.distro }}
          test_type: ${{ matrix.test_type }}
          ansible_version: ${{ matrix.ansible_version }}
          jinja2_version: ${{ matrix.jinja2_version }}
          python_version: ${{ matrix.python_version }}
